from flowscope.domain.strategies import (
    IndicatorStrategy,
    RangeStrategy,
    RangePercentualStrategy,
    TypicalPriceStrategy,
    MedianPriceStrategy,
    WeightedCloseStrategy,
    CLVStrategy,
    MoneyFlowMultiplierStrategy,
    BuyingPressureStrategy,
    SellingPressureStrategy,
    MoneyFlowVolumeStrategy,
    AverageTradeSizeStrategy,
    AverageFinancialTicketStrategy,
    VWAPStrategy,
    VolumeProfileStrategy,
    TopTickersStrategy,
    DailyEfficiencyStrategy,
    DailyMoneyFlowStrategy,
    DominanceScoreStrategy,
    FinancialDensityStrategy,
    TradeDensityStrategy,
    VolumeDensityStrategy,
    VWAPDistanceStrategy,
)
from flowscope.domain.engine import IndicatorEngine


def default_engine(tick_size: float = 0.01, top_n: int = 15) -> IndicatorEngine:
    engine = IndicatorEngine()
    engine.register(
        RangeStrategy(),
        TypicalPriceStrategy(),
        MedianPriceStrategy(),
        WeightedCloseStrategy(),
        CLVStrategy(),
        MoneyFlowMultiplierStrategy(),
        BuyingPressureStrategy(),
        SellingPressureStrategy(),
        MoneyFlowVolumeStrategy(),
        AverageTradeSizeStrategy(),
        AverageFinancialTicketStrategy(),
        RangePercentualStrategy(),
        DailyEfficiencyStrategy(),
        DailyMoneyFlowStrategy(),
        DominanceScoreStrategy(),
        FinancialDensityStrategy(),
        TradeDensityStrategy(),
        VolumeDensityStrategy(),
        VWAPDistanceStrategy(),
        VWAPStrategy(),
        VolumeProfileStrategy(tick_size),
        TopTickersStrategy(top_n),
    )
    return engine
